# Production profile for UTK hosting
# Usage:
#   bundle exec jekyll serve --config _config.yml,_config.utk.yml
#   bundle exec jekyll build --config _config.yml,_config.utk.yml

url: https://web.eecs.utk.edu
baseurl: /~mdjouadi

footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
  Hosted by the University of Tennessee, Knoxville.
